user@Kashyap-Laptop MINGW63 ~/Code/Whooga-MERN (main) $ git status On branch main Your branch is behind 'origin/main' by 5 commits, and can be fast-forwarded.   (use "git pull" to update your local branch)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .gitignore
        modified:   client/.gitignore
        modified:   client/package-lock.json
        modified:   server/package-lock.json

no changes added to commit (use "git add" and/or "git commit -a")

user@Kashyap-Laptop MINGW64 ~/Code/Whooga-MERN (main)
$ git pull
Updating 6bcd00f..6b65ecf
error: Your local changes to the following files would be overwritten by merge:
        client/package-lock.json
        server/package-lock.json
Please commit your changes or stash them before you merge.
Aborting